{"name": "test_cal_sum_1[5-5-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 9", "trace": "input1 = 5, input2 = 5, output = 9\n\n    @pytest.mark.parametrize(\"input1, input2, output\",\n                             [\n                                (2,3,5),\n                                (3,3,6),\n                                (5,5,9)\n                             ]\n                             )\n    def test_cal_sum_1(input1, input2, output):\n        result = sum(input1,input2)\n>       assert result == output\nE       assert 10 == 9\n\ntest_parameterization_demo.py:14: AssertionError"}, "parameters": [{"name": "input1", "value": "5"}, {"name": "input2", "value": "5"}, {"name": "output", "value": "9"}], "start": 1571396282363, "stop": 1571396282363, "uuid": "b343051e-9e63-4f4a-9fe7-eb2860de6ea2", "historyId": "4bd5596afca5a6dd3b0da560afc26110", "testCaseId": "116cea5827257391fc08b3ff5328f943", "fullName": "test_parameterization_demo#test_cal_sum_1", "labels": [{"name": "suite", "value": "test_parameterization_demo"}, {"name": "host", "value": "computer-PC"}, {"name": "thread", "value": "5220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parameterization_demo"}]}